=== jybrj/XML_Database_Modeling/TravelAgencyData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:annotation>
		<xs:documentation xml:lang="en">
Database of Travel Insurance Company
</xs:documentation>
	</xs:annotation>
	<xs:element name="Travel_Agency_Data" type="Travel_Agency_Data"/>
	<xs:complexType name="Client">
		<xs:sequence>
			<xs:element name="FirstName" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="LastName" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Dateofbirth" type="xs:date" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Nationality" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Age" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Gender" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Country" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="State" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="City" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Address" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Zipcode" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="PhoneNumber" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="EmailID" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Comments" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="Personal_Information">
		<xs:sequence>
			<xs:element name="Client" type="Client"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Booking">
		<xs:sequence/>
		<xs:attribute name="id" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="Amount_Paid">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="currency" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType mixed="true" name="Payment_details">
		<xs:sequence>
			<xs:element name="Card_Brand" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Card_Number" type="xs:long" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Amount_Paid" type="Amount_Paid" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType mixed="true" name="Family_Travel">
		<xs:sequence>
			<xs:element name="No_of_Families" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Adult_Members" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Below12_Members" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Above60_Members" type="xs:integer" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Additional_Info">
		<xs:sequence>
			<xs:element name="Solo_Travel" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Family_Travel" type="Family_Travel"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Booking_Information">
		<xs:sequence>
			<xs:element name="Booking" type="Booking"/>
			<xs:element name="Promo_Offer" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Contract_signed" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Payment_details" type="Payment_details"/>
			<xs:element name="Additional_Info" type="Additional_Info"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Tour_Price">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="currency" type="xs:string"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="Tour">
		<xs:sequence>
			<xs:element name="Tour_Category" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Tour_Type" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Tour_City" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Tour_Country" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Tour_Price" type="Tour_Price" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Tour_Activities" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Tour_Details" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="Tour_Information">
		<xs:sequence>
			<xs:element name="Tour" type="Tour"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Hotel">
		<xs:sequence/>
		<xs:attribute name="id" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="Hotel_Services">
		<xs:sequence>
			<xs:element name="Meals_Included" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Gym_Included" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Spa_Included" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Events_Included" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Accommodation_Information">
		<xs:sequence>
			<xs:element name="Hotel" type="Hotel"/>
			<xs:element name="Hotel_Name" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Hotel_City" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Hotel_Country" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Hotel_Address" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Hotel_Zipcode" type="xs:integer" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Hotel_RoomType" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="No_of_Rooms" type="xs:byte"/>
			<xs:element name="Hotel_Services" type="Hotel_Services" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Flight_Info">
		<xs:sequence>
			<xs:element name="FlightID" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="From_City" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="To_City" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Connection" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
			<xs:element name="C_FlightID" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="C_From_City" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="C_To_City" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="AirlineName" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="RentalCar">
		<xs:sequence>
			<xs:element name="RentalType" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Brand" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Model" type="xs:string" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Seating" type="xs:byte" minOccurs="0" maxOccurs="1"/>
			<xs:element name="Duration" type="xs:string" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Transport_Information">
		<xs:sequence>
			<xs:element name="Flight_Info" type="Flight_Info"/>
			<xs:element name="RentalCar" type="RentalCar"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Client_Data">
		<xs:sequence>
			<xs:element name="Personal_Information" type="Personal_Information" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Booking_Information" type="Booking_Information" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Tour_Information" type="Tour_Information" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Accommodation_Information" type="Accommodation_Information" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Transport_Information" type="Transport_Information" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Travel_Agency_Data">
		<xs:sequence>
			<xs:element name="Client_Data" type="Client_Data" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== jybrj/XML_Database_Modeling/TravelAgencyData.xml
<Travel_Agency_Data xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="TravelAgencyData.xsd">
	<Client_Data>
		<Personal_Information>
			<Client id='21500'>
				<FirstName>Brian</FirstName>
				<LastName>Whittaker</LastName>
				<Dateofbirth>1974-02-08</Dateofbirth>
				<Nationality>British</Nationality>
				<Age>48</Age>
				<Gender>Male</Gender>
				<Country>France</Country>
				<State>Auvergne-Rhône-Alpes</State>
				<City>Lyon</City>
				<Address>108 Rue de Menilmontant</Address>
				<Zipcode>69005</Zipcode>
				<PhoneNumber>086-655-2638</PhoneNumber>
				<EmailID>brian.whittaker@outlook.com</EmailID>
				<Comments>British National living in France with dual citizenship</Comments>
			</Client>
		</Personal_Information>
		<Booking_Information>
			<Booking id='Ref-0100'/>
			<Promo_Offer>true</Promo_Offer>
			<Contract_signed>true</Contract_signed>
			<Payment_details>Credit card
				<Card_Brand>Unionpay</Card_Brand>
				<Card_Number>6256421728425451</Card_Number>
				<Amount_Paid currency='euros'>131.651</Amount_Paid>
			</Payment_details>
			<Additional_Info>
				<Solo_Travel>false</Solo_Travel>
				<Family_Travel>true
					<No_of_Families>2</No_of_Families>
					<Adult_Members>4</Adult_Members>
					<Below12_Members>3</Below12_Members>
					<Above60_Members>1</Above60_Members>
				</Family_Travel>
			</Additional_Info>
		</Booking_Information>
		<Tour_Information>
			<Tour id='2149'>
				<Tour_Category>Domestic</Tour_Category>
				<Tour_Type>BeachTourism</Tour_Type>
				<Tour_City>Marseille</Tour_City>
				<Tour_Country>France</Tour_Country>
				<Tour_Price currency='euros'>335.750</Tour_Price>
				<Tour_Activities>Scubadiving, Surfing, Paragliding</Tour_Activities>
				<Tour_Details>5 days &amp; 6 nights</Tour_Details>
			</Tour>
		</Tour_Information>
		<Accommodation_Information>
			<Hotel id='FD2B'/>
			<Hotel_Name>Seascape Hotel</Hotel_Name>
			<Hotel_City>Marseille</Hotel_City>
			<Hotel_Country>France</Hotel_Country>
			<Hotel_Address>35 Rue Turenne</Hotel_Address>
			<Hotel_Zipcode>13011</Hotel_Zipcode>
			<Hotel_RoomType>Deluxe</Hotel_RoomType>
			<No_of_Rooms>3</No_of_Rooms>
			<Hotel_Services>
				<Meals_Included>Breakfast</Meals_Included>
				<Gym_Included>true</Gym_Included>
				<Spa_Included>false</Spa_Included>
				<Events_Included>false</Events_Included>
			</Hotel_Services>
		</Accommodation_Information>
		<Transport_Information>
			<Flight_Info>
				<FlightID>AFF377459C8C</FlightID>
				<From_City>Lyon</From_City>
				<To_City>Marseille</To_City>
				<Connection>false</Connection>
				<C_FlightID>not applicable</C_FlightID>
				<C_From_City>not applicable</C_From_City>
				<C_To_City>not applicable</C_To_City>
				<AirlineName>RyanAir</AirlineName>
			</Flight_Info>
			<RentalCar>
				<RentalType>Fullsize</RentalType>
				<Brand>Chevrolet</Brand>
				<Model>Impala</Model>
				<Seating>10</Seating>
				<Duration>5 days</Duration>
			</RentalCar>
		</Transport_Information>
	</Client_Data>
	<Client_Data>
		<Personal_Information>
			<Client id='215001'>
				<FirstName>Annika</FirstName>
				<LastName>Terrel</LastName>
				<Dateofbirth>1985-09-21</Dateofbirth>
				<Nationality>French</Nationality>
				<Age>36</Age>
				<Gender>Female</Gender>
				<Country>France</Country>
				<State>Rhône</State>
				<City>Caluire-et-Cuire</City>
				<Address>10 Chemin Jean Petit</Address>
				<Zipcode>69300</Zipcode>
				<PhoneNumber>029-863-5110</PhoneNumber>
				<EmailID>terrel.annika@gmail.com</EmailID>
				<Comments>No additional comments</Comments>
			</Client>
		</Personal_Information>
		<Booking_Information>
			<Booking id='Ref-0101'/>
			<Promo_Offer>false</Promo_Offer>
			<Contract_signed>true</Contract_signed>
			<Payment_details>Credit card

				<Card_Brand>Mastercard</Card_Brand>
				<Card_Number>2149822516049850</Card_Number>
				<Amount_Paid currency='euros'>243.996</Amount_Paid>
			</Payment_details>
			<Additional_Info>
				<Solo_Travel>false</Solo_Travel>
				<Family_Travel>true

					<No_of_Families>5</No_of_Families>
					<Adult_Members>8</Adult_Members>
					<Below12_Members>0</Below12_Members>
					<Above60_Members>2</Above60_Members>
				</Family_Travel>
			</Additional_Info>
		</Booking_Information>
		<Tour_Information>
			<Tour id='6304'>
				<Tour_Category>International</Tour_Category>
				<Tour_Type>CulturalTourism</Tour_Type>
				<Tour_City>Bogota</Tour_City>
				<Tour_Country>Colombia</Tour_Country>
				<Tour_Price currency='euros'>587.900</Tour_Price>
				<Tour_Activities>Walking Tour, Sightseeing, Museum visit</Tour_Activities>
				<Tour_Details>7 days &amp; 6 nights</Tour_Details>
			</Tour>
		</Tour_Information>
		<Accommodation_Information>
			<Hotel id='3D09'/>
			<Hotel_Name>Atlantis Pyramid Resort</Hotel_Name>
			<Hotel_City>Bogota</Hotel_City>
			<Hotel_Country>Colombia</Hotel_Country>
			<Hotel_Address>Av Miguel Aleman 232</Hotel_Address>
			<Hotel_Zipcode>110151</Hotel_Zipcode>
			<Hotel_RoomType>Double Room</Hotel_RoomType>
			<No_of_Rooms>5</No_of_Rooms>
			<Hotel_Services>
				<Meals_Included>Breakfast &amp; Weekend Buffet </Meals_Included>
				<Gym_Included>false</Gym_Included>
				<Spa_Included>false</Spa_Included>
				<Events_Included>true</Events_Included>
			</Hotel_Services>
		</Accommodation_Information>
		<Transport_Information>
			<Flight_Info>
				<FlightID>LV32XIEX13432</FlightID>
				<From_City>Paris</From_City>
				<To_City>NewYork</To_City>
				<Connection>true</Connection>
				<C_FlightID>NO146887643</C_FlightID>
				<C_From_City>NewYork</C_From_City>
				<C_To_City>Bogota</C_To_City>
				<AirlineName>AmericanAirlines</AirlineName>
			</Flight_Info>
			<RentalCar>
				<RentalType>Minivan</RentalType>
				<Brand>Kia</Brand>
				<Model>Sedona</Model>
				<Seating>16</Seating>
				<Duration>7 days</Duration>
			</RentalCar>
		</Transport_Information>
	</Client_Data>
	<Client_Data>
		<Personal_Information>
			<Client id='215002'>
				<FirstName>Jason</FirstName>
				<LastName>Smith</LastName>
				<Dateofbirth>1967-11-12</Dateofbirth>
				<Nationality>British</Nationality>
				<Age>55</Age>
				<Gender>Male</Gender>
				<Country>France</Country>
				<State>Savoie</State>
				<City>Aix-les-Bains</City>
				<Address>1 Avenue Charles de Gaulle</Address>
				<Zipcode>73100</Zipcode>
				<PhoneNumber>047-961-6010</PhoneNumber>
				<EmailID>j.smith@outlook.com</EmailID>
				<Comments>British Passport holder living in France</Comments>
			</Client>
		</Personal_Information>
		<Booking_Information>
			<Booking id='Ref-0102'/>
			<Promo_Offer>true</Promo_Offer>
			<Contract_signed>true</Contract_signed>
			<Payment_details>Credit card

				<Card_Brand>Voyager</Card_Brand>
				<Card_Number>8699641189618051</Card_Number>
				<Amount_Paid currency='euros'>150.325</Amount_Paid>
			</Payment_details>
			<Additional_Info>
				<Solo_Travel>false</Solo_Travel>
				<Family_Travel>true

					<No_of_Families>1</No_of_Families>
					<Adult_Members>2</Adult_Members>
					<Below12_Members>0</Below12_Members>
					<Above60_Members>0</Above60_Members>
				</Family_Travel>
			</Additional_Info>
		</Booking_Information>
		<Tour_Information>
			<Tour id='3278'>
				<Tour_Category>International</Tour_Category>
				<Tour_Type>EcoTourism</Tour_Type>
				<Tour_City>Tromso</Tour_City>
				<Tour_Country>Norway</Tour_Country>
				<Tour_Price currency='euros'>405.880</Tour_Price>
				<Tour_Activities>Northern Lights viewing, Arctic visit,Hiking</Tour_Activities>
				<Tour_Details>4 days &amp; 5 nights</Tour_Details>
			</Tour>
		</Tour_Information>
		<Accommodation_Information>
			<Hotel id='BG06'/>
			<Hotel_Name>Majestic Mantle Hotel</Hotel_Name>
			<Hotel_City>Tromso</Hotel_City>
			<Hotel_Country>Norway</Hotel_Country>
			<Hotel_Address>A Odhners gata 43</Hotel_Address>
			<Hotel_Zipcode>9021</Hotel_Zipcode>
			<Hotel_RoomType>Suite</Hotel_RoomType>
			<No_of_Rooms>1</No_of_Rooms>
			<Hotel_Services>
				<Meals_Included>Breakfast,Lunch &amp; Dinner </Meals_Included>
				<Gym_Included>true</Gym_Included>
				<Spa_Included>true</Spa_Included>
				<Events_Included>false</Events_Included>
			</Hotel_Services>
		</Accommodation_Information>
		<Transport_Information>
			<Flight_Info>
				<FlightID>VG474172985</FlightID>
				<From_City>Nice</From_City>
				<To_City>Stockholm</To_City>
				<Connection>true</Connection>
				<C_FlightID>FI93132175</C_FlightID>
				<C_From_City>Stockholm</C_From_City>
				<C_To_City>Oslo</C_To_City>
				<AirlineName>Lufthansa Airlines</AirlineName>
			</Flight_Info>
			<RentalCar>
				<RentalType>Premium</RentalType>
				<Brand>Ford</Brand>
				<Model>Crown</Model>
				<Seating>6</Seating>
				<Duration>5 days</Duration>
			</RentalCar>
		</Transport_Information>
	</Client_Data>
	<Client_Data>
		<Personal_Information>
			<Client id='215003'>
				<FirstName>Julie</FirstName>
				<LastName>Copeland</LastName>
				<Dateofbirth>1992-04-15</Dateofbirth>
				<Nationality>Belgian</Nationality>
				<Age>29</Age>
				<Gender>Female</Gender>
				<Country>France</Country>
				<State>Nord</State>
				<City>Lille</City>
				<Address>30 Place Sebastopol</Address>
				<Zipcode>59000</Zipcode>
				<PhoneNumber>073-391-2162</PhoneNumber>
				<EmailID>Juli_c92@yahoo.com</EmailID>
				<Comments>Belgian Passport holder living in France</Comments>
			</Client>
		</Personal_Information>
		<Booking_Information>
			<Booking id='Ref-0103'/>
			<Promo_Offer>true</Promo_Offer>
			<Contract_signed>true</Contract_signed>
			<Payment_details>Credit card

				<Card_Brand>AmericanExpress</Card_Brand>
				<Card_Number>3549116202861338</Card_Number>
				<Amount_Paid currency='euros'>183.489</Amount_Paid>
			</Payment_details>
			<Additional_Info>
				<Solo_Travel>true</Solo_Travel>
				<Family_Travel>false

					<No_of_Families>0</No_of_Families>
					<Adult_Members>0</Adult_Members>
					<Below12_Members>0</Below12_Members>
					<Above60_Members>0</Above60_Members>
				</Family_Travel>
			</Additional_Info>
		</Booking_Information>
		<Tour_Information>
